### ISSUE TITLE
wait wait wait so  long ....

### ISSUE THREAD

**Issue by xushuo** [benitojcv/hiveclient#1]
> node --harmony app.js

Example app listening at http://:::3000
{ Hive:
   { ConnectionString: 'jdbc:hive2://192.168.100.125:10000/;impersonnation_enable=true;',
     LoginTimeout: 10000,
     Port: 10000,
     Servers: [ '192.168.100.125' ],
     username: 'hadoop',
     query: 'show databases' } }
{ auth: 'NOSASL',
  host: '192.168.100.125',
  port: 10000,
  timeout: 10000,
  username: 'hadoop',
  hiveVer: '1.2.0',
  thriftVer: '0.9.2',
  hiveType: 0,
  maxRows: 5120,
  nullStr: 'NULL' }
  jshs2:configure port, : +0ms 10000
  jshs2:configure timeout, : +4ms 10000
  jshs2:configure hiveType, : +2ms 0
  jshs2:configure hiveVer, : +2ms 1.2.0
  jshs2:configure thirftVer, : +3ms 0.9.2
  jshs2:configure cdhVer, : +1ms null
  jshs2:CConnection OpenSession function start, ->  +27ms 192.168.100.125
  jshs2:CConnection OpenSession function start, ->  +2ms 10000
  jshs2:CConnection Initialize, username ->  +6ms hadoop
  jshs2:CConnection Initialize, password ->  +1ms
  jshs2:CConnection OpenSession request start,  +1ms { client_protocol: 7,
  username: 'hadoop',
  password: '',
  configuration: null }
..
.
.
.
no  response.....

why?

**Comment by benitojcv** [comment]
Make sure you are usign a correct version of CDH. I used Cloudera 5.4.2. You can download it from Cloudera Portal. 

Maybe you should review nodejs version. Sorry, I don't remind the version that i used for this example.

**Comment by xushuo** [comment]
@benitojcv   ,  I didn't use CDH, ..

![image](https://cloud.githubusercontent.com/assets/10043177/18333869/8440aef2-75a5-11e6-9b2b-6c3fb5660412.png)

HS2Util.prototype.HIVE_TYPE.HIVE = 0;        _ _ _ _Apache.

I just want to use nodejs  connection hive  ——direct 。
if you have some idea ，please tell me 。
this problem make me  mad  /(ㄒoㄒ)/~~

**Comment by benitojcv** [comment]
Sorry. I used CDH VM. Apache Hive is included in CDH. I can  your code into CDH VM for.

**Comment by benitojcv** [comment]
Sorry. I used CDH VM. Apache Hive is included in CDH. I can try your code into CDH VM to rule out other problems. You can download CDH here. http://www.cloudera.com/downloads/quickstart_vms/5-8.html

**Comment by xushuo** [comment]
@benitojcv  
Ok, I'll give it a try.
If i use nodejs connection hive ,do you have the other way?
In a word ,thank you!

**Comment by benitojcv** [comment]
Of course, you can use the command line hive client, but it run only inside CDH virtual machine. 
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Cli
if hive client run without problems, you have a connectivity or version problem. you should update package.json for include new versions of jshs2 module.

I recommend you that review the project https://github.com/imjuni/jshs2

**Comment by xushuo** [comment]
@benitojcv   OK ，i will  review the project https://github.com/imjuni/jshs2 . 
 i think it  is likely to have a connectivity problem. i will try again. 
thanks.
